// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0v8EH3JvEDTNW9qsFqQeykrMTigvyGy8',
    appId: '1:633054477323:web:a53e3b68c47ccf4f6a5b0e',
    messagingSenderId: '633054477323',
    projectId: 'b17-insta-clone',
    authDomain: 'b17-insta-clone.firebaseapp.com',
    storageBucket: 'b17-insta-clone.appspot.com',
    measurementId: 'G-ZZWJQ5ZSEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkNyNkWy7n-x-Xf130oEQOKpBc9_YrdA',
    appId: '1:633054477323:android:cefb8d0f9ec1968b6a5b0e',
    messagingSenderId: '633054477323',
    projectId: 'b17-insta-clone',
    storageBucket: 'b17-insta-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pDRoqJdNJMWXavFqNm1j6oUrzOLCt-4',
    appId: '1:633054477323:ios:0c989218f93e48436a5b0e',
    messagingSenderId: '633054477323',
    projectId: 'b17-insta-clone',
    storageBucket: 'b17-insta-clone.appspot.com',
    iosClientId: '633054477323-uhpqi67jnlo6075vt7k2538etb358tmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lessonPrepare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0pDRoqJdNJMWXavFqNm1j6oUrzOLCt-4',
    appId: '1:633054477323:ios:33587e90b10946ed6a5b0e',
    messagingSenderId: '633054477323',
    projectId: 'b17-insta-clone',
    storageBucket: 'b17-insta-clone.appspot.com',
    iosClientId: '633054477323-vphv5qs50jpfcrfo2r2l682ombkvo3hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lessonPrepare.RunnerTests',
  );
}
